sudo: false

language: node_js

node_js:
- '4'
- '5'
- '6'
- '7'
- '8'

cache:
  directories:
    - node_modules

notifications:
  email: false

matrix:
  include:
  - node_js: 7
    script:
      - npm run-script coverage
