sudo: false

language: node_js

node_js:
- '0.10'
- '0.12'
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'

cache:
  directories:
    - node_modules

notifications:
  email: false

matrix:
  include:
  - node_js: 7
    script:
      - npm run-script coverage
